### PR TITLE
Demo / example

### PR DESCRIPTION
**Pull request by ajsb85**
Hi @freaktechnik 
With `sdk/ui/button/action` work perfect. 
Does not need workaround.

### CODE REVIEW

**Comment by freaktechnik** [comment]
The workaround is for when the button is moved to the menu panel or the overflow panel, where it will close it immediately without the workaround.

Further I feel, that if there is a demo there should also be a package.json, since this is a module to be used within an extension and if it's just about single files there are already listings in the docs, or actually fully working code (including icon) in the test suite.

**Comment by ajsb85** [comment]
Yes, I try to fix the `ToggleButton` using the **workaround** but the error persist.
And using `sdk/ui/button/action` work perfect.

**Comment by freaktechnik** [comment]
Hmm, there does indeed seem to be some brokenness, I've opened #26 for that.

**Comment by ajsb85** [comment]
jpm

**Comment by freaktechnik** [comment]
The GIF does not demonstrate behaviour of the button inside a panel, which is what the workaround fixes. I'll merge this pull tomorrow and extend the demo once I've found out what's going on in regards to #26

**Comment by freaktechnik** [comment]
Thanks for the patch!

**Pull request merged**
